[package]
name = "console_client"
version = "0.1.0"
authors = ["Sergey"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_of_life_logic = { path="../game_of_life_logic" }
rand = "0.5.5"